.TH u2ps 1
'''
.SH NAME
u2ps \- unicode text to PostScript converter
'''
.SH SYNOPSIS
u2ps [\fIoptions\fR] \fIinput-file\fR [\fIoutput-file\fR]
'''
.SH DESCRIPTION
\fBu2ps\fR produces printable PostScript document from supplied text,
handling arbitrary Unicode characters.
'''
.SH USAGE
Input file name must be supplied. Output file name is optional,
with the default value \fIinput-file\fR.ps.
Input file name may be "-", in which case stdin will be used.

Output file is generated in several passes, and thus can not be piped.

Short options may be squashed: \fB-Hiw\fR equals \fB-H -i -w\fR.
Both \fB--\fIoption\fB=\fIvalue\fR and \fB--\fIoption\fR \fIvalue\fR forms
can be used. Use \fB--\fR to terminate option processing.
Whenever argument is required for a long option, same goes for the short one.
'''
.SS Input-related options
.IP "\fB-e\fR / \fB--encoding=\fIencoding\fR" 4
Input file encoding. May be anything \fBiconv(3)\fR library understands,
run 'iconv --list' to get full list. Defaults to current locale encoding.
.IP "\fB--opt-encoding=\fIname\fR" 4
Options encoding (for --header/--footer) [utf-8]
.IP "\fB-T\fR/\fB--tab=\fIn\fR" 4
Tab size.
.IP "\fB-a\fR/\fB--no-ansi\fR" 4
Do not interpret ANSI terminal control sequences.
'''
.SS Paper setup
.IP "\fB-P\fR/\fB--paper=name\fR" 4
Paper name, or size in mm (WxH)
.IP "\fB-M\fR/\fB--margins=values\fR" 4
Margins, in pt; a single number, or V:H, or T:R:B:L.
Note the margins are for the text area only. Headings, line numbers and
wrap marks will be printed outside of specified region.
.IP "\fB-r\fR/\fB--landscape\fR" 4
Rotate to landscape orientation
'''
.SS Font size selection
Use only one of these options. Paper size will be used to determine the other two.
.IP "\fB-s\fR/\fB--font-size=\fIn\fR" 4
Font size (pt)
.IP "\fB-C\fR/\fB--columns=\fIn\fR" 4
Columns per line.
.IP "\fB-L\fR/\fB--lines=\fIn\fR" 4
Lines per page
'''
.SS Fonts setup
Note unicode printing is done with fontsets, not regular PostScript fonts.
Check /usr/share/u2ps/ps/FontSet for a list.
.IP "\fB-f\fR/\fB--font-set=\fIname\fR" 4
Primary font set [FreeMono]
.IP "\fB--aux-font-set=\fIname\fR" 4
Auxilliary font set [Times-Roman]
.IP "\fB--lnum-font=\fIname\fR" 4
Font to use for line numbers [Times-Roman]
.IP "\fB--head-font-size=\fIn\fR" 4
Headings font size (pt)
.IP "\fB--lnum-font-size=\fIn\fB" 4
Line numbers font size (pt)
'''
.SS Output control options:
.IP "\fB-w\fR/\fB--wrap\fR" 4
Wrap long lines
.IP "\fB-W\fR/\fB--wrap-mark\fR" 4
Wrap long lines and set wrap marks
.IP "\fB-i\fR/\fB--inverse\fR" 4
Inverse (white text on black background) mode. Does not change other
colors, so red will still be red. Use this to make the page
look as close to a real terminal as possible. Can be useful for 
making "terminal screenshots" or rendering ASCII art, but hardly
suitable for printing.
.IP "\fB-l\fR/\fB--numbers\fR" 4
Print line numbers
.IP "\fB--start-line=\fIn\fR" 4
First line number, instead of default 1.
.IP "\fB-b\fR/\fB--bookish\fR" 4
Swap left and right headings on even pages.
.IP "\fB-t\fR/\fB--title=\fIstring\fR" 4
Page title.
.IP "\fB-H\fR/\fB--no-headings\fR" 4
Do not print default headings
.IP "\fB--header=\fR..." 4
.IP "\fB--header-left=\fR..." 4
.IP "\fB--header-right=\fR..." 4
Page headings: centered, left and right aligned.
.IP "\fB--footer=\fR..." 4
.IP "\fB--footer-left=\fR..." 4
.IP "\fB--footer-right=\fR..." 4
Page footers.
'''
.SS Postscript options
.IP "\fB-F\fR/\fB--no-fonts\fR" 4
Do not embed fonts
.IP "\fB-A\fR/\fB--all-fonts\fR" 4
Embed all fonts, including standard postscript 35
.IP "\fB--no-notdef\fR" 4
Do not automatically embed notdef font
.IP "\fB-E\fR/\fB--no-resources\fR"
Do not embed resources / do not post-process output file (see man page on how to use this).
'''
.SS Misc options
.IP "\fB--keep\fR" 4
Do not delete temporary files
.IP "\fB-v\fR/\fB--verbose\fR" 4
Be verbose
.IP "\fB-G\fR/\fB--gs=\fIpath\fR" 4
Ghostscript command
'''
.SH NOTES
.SS Font reduction
To allow large fontsets and at the same time produce files of reasonable
size, u2ps embeds only fonts and glyphs actually used into the final document.
This is done by passing initial document through gs -sDEVICE=nullpage,
collecting glyph usage statistics and dumping relevant parts of the fonts
loaded by gs.

Ghostscript run is the most complicated and cpu-intensive part of u2ps operation.

Embedding fonts (and other resources) into document is not, in fact, necessary
if gs knows where to look for them. In such case you can make u2ps run
much faster by using -E option. Just make sure to pass -I/usr/share/u2ps/ps to gs
when handling files produced by u2ps -E, or otherwise make u2ps resources available.
'''
.SS PostScript printers
u2ps relies on non-standard \fBglyphwidth\fR operator to center and right-align headings.
In case postscript interpreter in your printer lacks this operator, you are likely to get
misaligned headings.
'''
.SS Standard PostScript fonts
Unless told otherwise, u2ps does not embed standard fonts (Times-Roman, Courier and such).
Most of the time it works well. However, range coverage outside of basic Latin1
is not guaranteed for standard fonts, and the fonts bundled with Ghostscript tend to have
more glyphs than fonts in a typically printer.

In case you get notdef marks on printouts that weren't there in Ghostscript, consider
embedding standard fonts as well (\fB-A\fR option).
'''
.SS TrueType fonts
Normally u2ps relies on Ghostscript to load TT fonts. However, Ghostscript can not
handle TT fonts without "post" table properly. When loaded directly by Ghostscript, 
such fonts get non-standard (and non-usable) glyph names, which makes them useless
for u2ps.

There is a workaround: u2ps comes with ttf2pt42 utility, which converts TTF into
Type42 postscript font with usable glyph names. The resulting .pfa font file must 
be placed somewhere gs can find it, and listed in relevant Fontmap file.

For u2ps-specific fonts, this should probably be /usr/share/u2ps/ps/fonts and
/usr/share/u2ps/ps/Fontmap respectively.
'''
.SS Font licensing
When embedding fonts, u2ps assumes you have rights to do so. Not checks are performed
and no warnings are issues even for protected fonts.
'''
.SH AUTHOR
Written by Alex Suykov \fT<alex.suykov@gmail>\fR
.br
Feel free to send bug reports and suggestions.
'''
.SH SEE ALSO
\fBgs(1)\fR, \fBhighlight(1)\fR, \fBpsnup(1)\fR, \fBpsbook(1)\fR, \fBpsselect(1)\fR,
\fBepstopdf(1)\fR, \fBps2pdf\fR.

Similar utilities: \fBa2ps(1)\fR, \fBpaps(1)\fR, \fBtexttops\fR from cups package.
